name: crow
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flame: ^1.6.0
  flutter:
    sdk: flutter
  google_mobile_ads: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Kaph
      fonts:
        - asset: assets/fonts/Kaph-Regular.ttf
        - asset: assets/fonts/Kaph-Italic.ttf
          style: italic
